name: 'civicautomotive'
version: '1.0.0'
profile: 'default'

model-paths:    ["models"]
test-paths:     ["tests"]
seed-paths:     ["seeds"]
macro-paths:    ["macros"]
snapshot-paths: ["snapshots"]
docs-paths:     ["docs"]
analysis-paths: ["analyses"]

models:
  civicautomotive:

    staging:
      +materialized: view
      coches:
        +schema: public
        +database: "{{ env_var('DBT_ENVIRONMENTS') }}_SILVER_DB"

    marts:
      +materialized: table
      core:
        +schema: core
        +database: "{{ env_var('DBT_ENVIRONMENTS') }}_GOLD_DB"
        intermediate:
          +materialized: view
          +schema: intermediate
        # fact_ventas sobreescribe la materialización a incremental
        fact_ventas:
          +materialized: incremental
          +incremental_strategy: merge
          +unique_key: id_venta

seeds:
  civicautomotive:
    +schema: seed_data
    +database: "{{ env_var('DBT_ENVIRONMENTS', 'FAIL') }}_BRONZE_DB"

snapshots:
  civicautomotive:
    +transient: false
    +schema: snapshots
    +database: "{{ env_var('DBT_ENVIRONMENTS') }}_SILVER_DB"

tests:
  +severity: error
  +store_failures: true         
  +store_failures_as: view